const colors = {
    header: '#333333',
    primary: '#173EA5',
    background:'#ffffff',
    grey:'#E6E6E6',
    
    buttonText:'#ffffff',
    danger:'#CD3131',
    //text colors
    text:'#000000',
    textLight:'#666666',
    textGreyDark:'#333333',
    //Types color pokemon
    allTypes:'#333333',
    waterType:'#5090D6',
    dragonType:'#0B6DC3',
    electricType:'#F4D23C',
    fairyType:'#EC8FE6',
    ghostType:'#5269AD',
    fireType:'#FF9D55',
    iceType:'#73CEC0',
    grassType:'#63BC5A',
    fightingType:'#CE416B',
    normalType:'#919AA2',
    darkType:'#5A5465',
    ironType:'#5A8EA2',
    rockType:'#C5B78C',
    psychicType:'#FA7179',
    groundType:'#D97845',
    poisonType:'#B567CE',
    flyingType:'#89AAE3',
    bugType:'#91C12F',
    //types backgroundcolor
    waterBackground:'#EBF1F8',
    dragonBackground:'#E4EEF6',
    electricBackground:'#FBF8E9',
    fairyBackground:'#FBF1FA',
    ghostBackground:'#EBEDF4',
    fireBackground:'#FCF3EB',
    iceBackground:'#F1FBF9',
    grassBackground:'#EDF6EC',
    fightingBackground:'#F8E9EE',
    normalBackground:'#F1F2F3',
    darkBackground:'#ECEBED',
    ironBackground:'#ECF1F3',
    rockBackground:'#F7F5F1',
    psychicBackground:'#FCEEEF',
    groundBackground:'#F9EFEA',
    poisonBackground:'#F5EDF8',
    flyingBackground:'#F1F4FA',
    bugBackground:'#F1F6E8'
  };
  
  export default colors;